/* ============================================================
   Fake but realistic Codeforces data for handle "jjelloo"
   ============================================================ */
  // ---- user / rating ----
  const USER = {
    handle: "jjelloo",
    rating: 1647,
    maxRating: 1689,
    rank: "Expert",
    maxRank: "Expert",
    contribution: 42,
    friends: 18,
    registered: "2023-09-02",
    avatarHue: 255,
  };

  // rating history: contest-by-contest
  const RATING_HISTORY = [
    { c: "Codeforces Round 901 (Div. 2)",  date: "2024-10-12", rating: 1148, delta: +148 },
    { c: "Educational Round 156",          date: "2024-11-03", rating: 1213, delta: +65  },
    { c: "Codeforces Round 910 (Div. 2)",  date: "2024-11-21", rating: 1189, delta: -24  },
    { c: "Codeforces Round 915 (Div. 2)",  date: "2024-12-09", rating: 1302, delta: +113 },
    { c: "Good Bye 2024",                  date: "2024-12-30", rating: 1356, delta: +54  },
    { c: "Educational Round 161",          date: "2025-01-18", rating: 1421, delta: +65  },
    { c: "Codeforces Round 925 (Div. 2)",  date: "2025-02-04", rating: 1388, delta: -33  },
    { c: "Codeforces Round 931 (Div. 2)",  date: "2025-02-22", rating: 1467, delta: +79  },
    { c: "Educational Round 165",          date: "2025-03-15", rating: 1512, delta: +45  },
    { c: "Codeforces Round 938 (Div. 3)",  date: "2025-04-02", rating: 1559, delta: +47  },
    { c: "Codeforces Round 944 (Div. 2)",  date: "2025-04-27", rating: 1498, delta: -61  },
    { c: "Codeforces Round 950 (Div. 2)",  date: "2025-06-09", rating: 1571, delta: +73  },
    { c: "Educational Round 170",          date: "2025-08-14", rating: 1604, delta: +33  },
    { c: "Codeforces Round 962 (Div. 2)",  date: "2025-09-22", rating: 1689, delta: +85  },
    { c: "Codeforces Round 971 (Div. 2)",  date: "2025-11-10", rating: 1622, delta: -67  },
    { c: "Educational Round 176",          date: "2026-01-19", rating: 1668, delta: +46  },
    { c: "Codeforces Round 988 (Div. 2)",  date: "2026-03-08", rating: 1611, delta: -57  },
    { c: "Codeforces Round 995 (Div. 2)",  date: "2026-05-24", rating: 1647, delta: +36  },
  ];

  // ---- solved problems ----
  // note may contain $inline$ and $$display$$ LaTeX
  const P = (contestId, index, name, rating, tags, solvedAt, attempts, note, statement) =>
    ({ id: contestId + index, contestId, index, name, rating, tags, solvedAt, attempts, note, statement });

  const PROBLEMS = [
    P(1987, "D", "World is Mine", 1900, ["dp","greedy","games"], "2026-05-31", 4,
      "Alice & Bob alternately eat cakes; Bob deletes to minimize Alice's count. Key realization: sort descending, then it's a DP over *how many of the top cakes Bob spends a turn destroying*.\n\nState $dp[i][j]$ = considering the $i$-th largest cake, Bob has 'wasted' $j$ destroy-turns so far. Alice eats a cake iff $i - j > $ (cakes Bob already removed). Transition compares $j$ against the index.\n\nGot TLE first with $O(n^3)$, pruned to $$O(n^2)$$ by noting $j \\le i$.",
      "Initially there are $n$ cakes, the $i$-th has tastiness $a_i$. Alice wants to maximize the number of distinct-tastiness cakes she eats; Bob wants to minimize it. They alternate, Alice first…"),
    P(1986, "E", "Beautiful Array", 1600, ["greedy","math","sortings"], "2026-05-28", 2,
      "Sort, then greedily pair within residue classes mod $k$. The cost telescopes — pair adjacent elements in each bucket. Watch the parity: an odd bucket size means one element is the 'pivot' you don't touch.",
      "An array is beautiful if you can permute it so $a_i \\equiv a_1 \\pmod k$ pattern holds… minimize total increment operations."),
    P(1985, "G", "D-Function", 1700, ["combinatorics","math","number theory"], "2026-05-20", 3,
      "$D(n)$ = digit sum condition. Count $x$ in $[10^l, 10^r)$ with $D(k\\cdot x)=k\\cdot D(x)$ — equivalent to *no carries* when multiplying by $k$. Per digit there are $\\lfloor 10/k \\rfloor$ valid choices, so the answer is a clean geometric series $$\\sum_{i=l}^{r-1} c^{i}\\cdot(c-1)$$ where $c=\\lceil 10/k\\rceil$.",
      "Let $D(n)$ be the digit sum of $n$. Count integers $x$ such that $D(k \\cdot x) = k \\cdot D(x)$ and $10^l \\le x < 10^r$, modulo $10^9+7$."),
    P(1984, "C", "Magnitude", 1400, ["dp","greedy","math"], "2026-05-18", 1,
      "Two passes. The best moment to take the absolute value is exactly once, right after the prefix sum reaches its minimum. Answer = (final sum) − 2·(min prefix, capped at 0).",
      "You start with $c=0$ and process $a_1..a_n$. Each step either $c{+}{=}a_i$ or $c = |c + a_i|$. Maximize final $c$."),
    P(1982, "D", "Beauty of the mountains", 1900, ["math","number theory","data structures"], "2026-05-10", 5,
      "2D prefix sums + a Bezout/gcd feasibility check. The difference you must close has to be divisible by $\\gcd$ of the two region sizes. Spent ages on an off-by-one in the 2D prefix.",
      "Grid of mountains, some snowy. One operation adds $k$ to every cell in a chosen sub-rectangle. Make snowy and non-snowy totals equal."),
    P(1980, "F", "Field Should Not Be Empty", 1700, ["data structures","math"], "2026-05-03", 3,
      "Segment tree with lazy add, counting positions where a swap creates a new 'good' index. Tricky contribution bookkeeping.",
      "A permutation $p$; a position $i$ is good if $\\min(p_1..p_i) \\cdot \\max(p_i..p_n)$ equals $i \\cdot$ something… count good positions over all single swaps."),
    P(1979, "C", "Earning on Bets", 1300, ["constructive algorithms","math"], "2026-04-29", 2,
      "Set each bet to $L / k_i$ where $L = \\operatorname{lcm}(k_i)$. Then every outcome pays exactly $L$. Feasible iff $\\sum L/k_i < L$.",
      "There are $n$ outcomes with multipliers $k_i$. Distribute integer coins so that for every outcome the payout strictly exceeds total coins spent."),
    P(1976, "D", "Invertible Bracket Sequences", 1900, ["combinatorics","data structures","trees"], "2026-04-21", 4,
      "Count substrings whose inversion is still balanced. Reduce to: on the prefix-balance walk, count sub-segments that stay $\\ge$ their endpoints' min. Used a stack + contribution counting.",
      "A regular bracket sequence; invert a substring (swap '(' and ')'). Count substrings whose inversion keeps the whole sequence regular."),
    P(1975, "C", "Chips on a Line", 1500, ["bitmasks","dp","greedy"], "2026-04-15", 2,
      "Fibonacci-base representation! Every configuration reduces to a canonical Zeckendorf-like form. Count distinct costs via DP over the normalized chip count.",
      "$n$ chips on a number line of $x$ points; a move merges/splits chips by Fibonacci rules. Count distinct minimum costs over all placements of $n$ chips."),
    P(1973, "B", "Cat, Fox and the Lonely Array", 1300, ["binary search","bitwise","two pointers"], "2026-04-11", 1,
      "Binary search the window length $k$; check with a sliding OR over fixed-width windows. The OR is monotone so feasibility is monotone in $k$.",
      "Array is $k$-good if every length-$k$ subarray has bitwise OR equal to the OR of the whole array. Find the minimum such $k$."),
    P(1969, "C", "Minimizing the Sum", 1600, ["dp"], "2026-04-04", 2,
      "Since each element can spread to at most $k$ neighbours, $dp[i][j]$ over the first $i$ elements with $j$ operations used; inner loop tries replacing a window with its min.",
      "Array $a$; in one op set $a_i = a_j$ for adjacent $i,j$. With at most $k$ ops minimize the array sum."),
    P(1968, "E", "Cells Arrangement", 1400, ["constructive algorithms","greedy"], "2026-03-30", 3,
      "Constructive: put cells on the main diagonal plus $(1,2)$ to force every Manhattan distance from $0..2(n-1)$ to appear. Took a few tries to see the $(1,2)$ trick.",
      "Place $n$ cells in an $n\\times n$ grid maximizing the number of distinct pairwise Manhattan distances."),
    P(1966, "C", "Everything Nim", 1500, ["games","greedy","sortings"], "2026-03-22", 2,
      "Sort piles, dedupe, look at the first gap $>1$. Standard Nim-flavoured parity argument on distinct pile sizes.",
      "Piles of stones; a move removes $k$ stones from every non-empty pile ($k$ fixed per move, $\\le$ smallest pile). Last to move wins."),
    P(1965, "B", "Missing Subsequence Sum", 1500, ["bitmasks","constructive algorithms","dp"], "2026-03-08", 4,
      "Build powers of two up to $k-1$, skip $k$, then add a tail so every sum except $k$ is reachable. Classic subset-sum construction.",
      "Construct a sequence so every integer in $[1,n]$ except $k$ is a subset-sum, and $k$ itself is not."),
    P(1955, "D", "Inaccurate Subsequence Search", 1300, ["data structures","two pointers"], "2026-02-28", 1,
      "Sliding window of length $m$ tracking how many letters meet the required count. Pure two-pointer.",
      "Count windows of length $m$ in $a$ that contain at least $k$ matching elements with template $b$."),
    P(1951, "C", "Ticket Hoarding", 1300, ["greedy","sortings"], "2026-02-20", 1,
      "Sort prices ascending, buy cheapest first; the $i$-th purchased day adds a marginal $m\\cdot$(days so far) penalty. Greedy with a running multiplier.",
      "Buy $m$ tickets over $n$ days; price on a day rises by the number bought on earlier days. Minimize total cost."),
    P(1950, "F", "Equal Product", 1600, ["brute force","math","number theory"], "2026-02-11", 3,
      "Enumerate divisor pairs of the target product; for each factor pair check it fits the $[l,r]$ box. $O(\\sqrt{P})$ factor enumeration.",
      "Find $x_1 \\le x_2$ and $y_1 \\le y_2$ in given ranges with $x_1 x_2 = y_1 y_2 = P$ and all four distinct."),
    P(1948, "D", "Tandem Repeats?", 1600, ["binary search","brute force","dp","hashing","strings"], "2026-02-03", 4,
      "For each candidate period $p$, scan and count matches where both chars agree or one is '?'. Longest run $\\ge p$ gives a tandem of length $2p$.",
      "A string with '?' wildcards. Find the longest substring that can become a tandem repeat (first half equals second half)."),
    P(1944, "C", "Bitwise Operations", 1400, ["bitmasks","greedy"], "2026-01-26", 2,
      "Prefix XOR/AND properties. If the whole-array XOR is nonzero, first player wins instantly; otherwise reduce to a smaller parity case.",
      "A game on bitwise XOR of a chosen subarray; determine the winner under optimal play."),
    P(1942, "C", "Bessie's Birthday Cake", 1500, ["geometry","greedy","math"], "2026-01-19", 3,
      "Polygon triangulation: already-chosen vertices fix some triangles; greedily fill the gaps of even size first since they yield more triangles per added vertex.",
      "A regular polygon with some chosen vertices; add up to $y$ more to maximize non-overlapping triangles in a triangulation."),
    P(1937, "C", "Save Talents", 1400, ["binary search","greedy"], "2026-01-11", 2,
      "Binary search on the answer; greedily check feasibility in linear time. Monotone predicate made it clean.",
      "Maximize the minimum talent level achievable under a budget of training operations."),
    P(1933, "E", "Turtle vs. Rabbit Race", 1600, ["binary search","greedy","math"], "2025-12-20", 3,
      "The score as a function of how many segments you run is unimodal — ternary search per query. Careful with the discrete peak (check both sides).",
      "Score accumulates as $c, c-1, c-2,\\dots$ over consecutive segments; choose a start and length to maximize, answer queries."),
    P(1931, "G", "One-Dimensional Puzzle", 1900, ["combinatorics","math"], "2025-12-12", 4,
      "Four piece types in a chain; the arrangement is forced up to interleaving two independent stars-and-bars choices. Answer = product of two binomials (with edge cases when counts are zero).",
      "Count distinct ways to assemble a 1-D jigsaw from four bracket-like piece types, modulo $998244353$."),
    P(1925, "B", "A Balanced Problemset?", 1100, ["greedy","math","number theory"], "2025-11-28", 1,
      "Maximize the GCD of $n$ parts summing to $x$: it must divide $x$, so take the largest divisor $d$ of $x$ with $x/d \\ge n$.",
      "Split $x$ into exactly $n$ positive parts maximizing their GCD."),
    P(1922, "D", "Berserk Monsters", 1600, ["data structures","implementation"], "2025-11-15", 3,
      "Doubly-linked list of monsters; only neighbours of dying monsters can die next round, so maintain a 'to-check' set. Amortized linear.",
      "Monsters in a row; each round a monster dies if its neighbours' total attack exceeds its defense. Report deaths per round."),
    P(1918, "C", "XOR-distance", 1400, ["bitwise","greedy","math"], "2025-10-30", 2,
      "Go bit by bit from the top. The highest differing bit is fixed; below it greedily flip to shrink $|(a\\oplus x)-(b\\oplus x)|$ while staying $\\le k$.",
      "Choose $0 \\le x \\le k$ minimizing $|(a \\oplus x) - (b \\oplus x)|$."),
    P(1915, "F", "Greetings", 1500, ["data structures","sortings"], "2025-10-18", 2,
      "Sort by start, count inversions on end coordinates with a BIT. Classic 'count pairs that overtake'.",
      "People on a line with start/end points; count ordered pairs where one fully overtakes another."),
    P(1913, "D", "Array Collapse", 1700, ["data structures","dp"], "2025-09-29", 4,
      "Monotonic stack defines which minima can survive; DP over reachable prefixes with a stack-based transition. Prefix sums of dp.",
      "Repeatedly remove elements keeping at least one minimum of a chosen subsegment. Count distinct resulting arrays."),
    P(1907, "F", "Build Permutation", 1600, ["constructive algorithms","graphs","greedy"], "2025-09-10", 3,
      "Model fixable positions as a graph; connected components must each be solvable. Constructive assignment within components.",
      "Construct a permutation matching constraints given as forbidden value-position pairs."),
    P(1900, "C", "Tree XOR", 1500, ["dfs and similar","graphs","trees"], "2025-08-22", 2,
      "Root anywhere, do a reroot DP. Cost of flipping a subtree edge scales with the subtree size; accumulate via two DFS passes.",
      "Make all node values equal by XOR-ing subtrees; each operation costs the subtree size. Minimize total cost."),
    P(1896, "B", "AB Flipping", 1000, ["greedy","strings"], "2025-08-05", 1,
      "Each 'AB' can be turned to 'BA', bubbling A's right and B's left. Count maximum operations = matched AB pairs greedily.",
      "Given a string of A/B, repeatedly replace 'AB' with 'BA'… maximize operations."),
    P(1891, "C", "Smilo and Monsters", 1400, ["greedy","math","two pointers"], "2025-07-19", 2,
      "Two pointers from smallest & largest pile. Spend 'charged' kills on the big piles; halve the work with the combo mechanic.",
      "Monster groups; you can kill one at a time (building combo) or unleash the combo to wipe a group. Minimize total actions."),
    P(1884, "C", "Medium Design", 1400, ["data structures","greedy","sortings"], "2025-07-01", 2,
      "Only the global min ($=0$) and max matter. Sweep candidate maxima, use a difference array to know how many segments would raise the min.",
      "Choose a subset of range-add segments to maximize (max value − min value) over the array."),
    P(1879, "D", "Sum of XOR Functions", 1800, ["bitmasks","dp","math"], "2025-06-14", 3,
      "Per bit, prefix-XOR splits indices into 0/1 classes. The contribution counts pairs weighted by $(j-i)$, so track counts *and* index sums per class.",
      "Sum over all subarrays of $f(l,r)\\cdot(r-l+1)$ where $f$ is the XOR of the subarray, modulo $10^9+7$."),
    P(1873, "G", "ABBC or BACB", 1500, ["greedy","strings"], "2025-05-28", 2,
      "Split on 'A' runs; coins = (#A) capped, but the largest gap of B's between A's can't all be collected — subtract the biggest B-block once.",
      "A string of A/B; operations 'AB'→'BC' style moves earn coins. Maximize coins."),
    P(1862, "E", "Kolya and Movie Theatre", 1400, ["data structures","dp","greedy","sortings"], "2025-05-10", 2,
      "Pick at most $m$ positive entries; decay penalty depends only on the *last* chosen index. Sort-free greedy with a min-heap of the top $m$ values.",
      "Maximize $\\sum a_{i} - d\\cdot(\\text{last index})$ choosing at most $m$ indices."),
    P(1857, "F", "Maximum Strength", 1700, ["math"], "2025-04-22", 3,
      "Digit-DP style over the two numbers; the max difference is achieved by maximizing each digit place independently after the first differing place.",
      "Maximize the 'strength' (digit-wise absolute difference) between any two chosen numbers in a range."),
    P(1850, "H", "The Third Letter", 1900, ["dfs and similar","dsu","graphs"], "2025-04-03", 4,
      "Weighted DSU: store each node's offset to its root; on union check consistency of the difference constraint. Contradiction ⇒ impossible.",
      "Soldiers with relative-position constraints $x_a - x_b = d$. Decide if a consistent 1-D placement exists."),
    P(1843, "F", "Omsk Metro", 1700, ["data structures","dp","trees"], "2025-03-14", 4,
      "Max-subarray (Kadane) values are mergeable, so maintain them per tree node as it grows; a queried path's max subarray answers the subset-sum reachability.",
      "A growing tree of $\\pm1$ values; for path queries decide if some subset of the path sums to a target."),
    P(1837, "E", "Playoff Fixing", 1800, ["combinatorics","implementation","math"], "2025-02-24", 3,
      "Bracket is a binary tree; fill known seeds bottom-up and multiply the free choices at each round (factorials of unknown placements).",
      "Count ways to fill an unknown playoff bracket consistent with given winners, modulo $998244353$."),
  ];

  // ---- canonical tag → display & color group ----
  const TAG_GROUPS = {
    "dp": "DP", "greedy": "Greedy", "math": "Math", "graphs": "Graphs",
    "data structures": "Data Structures", "binary search": "Binary Search",
    "number theory": "Number Theory", "strings": "Strings",
    "constructive algorithms": "Constructive", "trees": "Trees",
    "geometry": "Geometry", "bitmasks": "Bitmasks", "combinatorics": "Combinatorics",
    "implementation": "Implementation", "dfs and similar": "DFS / Graph Search",
    "two pointers": "Two Pointers", "sortings": "Sorting", "games": "Game Theory",
    "dsu": "DSU", "bitwise": "Bitwise", "hashing": "Hashing", "brute force": "Brute Force",
  };

export { USER, RATING_HISTORY, PROBLEMS, TAG_GROUPS };
